import landingPhoto from '../assets/img/about-landing.png'
import Landing from "../components/Landing"

const description = "to jeset opis strony lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem lorem"

const About = () => {
  return <div className="About">
  <Landing image={landingPhoto} header={"O nas"} description={description} btn={"Umów się"}/>
  <p style={{lineHeight: "40px", padding: "150px"}}>
    Lorem ipsum dolor, sit amet consectetur adipisicing elit. Similique dolorem ea consequatur id in quo saepe ex sapiente obcaecati nisi veritatis provident nemo minus totam, ipsam velit alias doloribus quibusdam nulla iusto modi! Molestias tenetur veniam labore! Aspernatur minima architecto tempora quos ab quo? Sunt cumque esse quod, magni repellendus, incidunt facilis voluptatibus non illo nulla dolore illum tempore tenetur ipsum soluta expedita! Velit, numquam illo aliquid ratione quae minus minima sed debitis neque id est, quis reiciendis vero vitae ipsam fuga repudiandae libero autem consequatur rem. Sunt totam, fugiat architecto aspernatur, praesentium magni commodi quis obcaecati dolore reprehenderit iste.
    Rerum ratione, qui velit illum commodi consequuntur nemo corrupti sed ducimus in modi sunt molestias esse minima voluptas enim nam, recusandae ab corporis. Consequuntur praesentium, delectus deleniti distinctio repellendus asperiores doloribus aut quaerat nobis voluptate, ipsam, est sint? Omnis exercitationem ducimus impedit quod vitae quia provident ullam nobis fuga qui maxime nulla sunt totam tempora nam tempore molestias quaerat quos reiciendis quibusdam voluptates porro voluptate, assumenda nesciunt. Sapiente perspiciatis libero quis quia at et ducimus nisi tempora reprehenderit rerum dolorem atque deleniti, ex magnam veritatis aliquid omnis dolor officiis pariatur nobis, voluptate, alias repellat. Tenetur praesentium corrupti consequatur facilis labore!
    Reiciendis doloribus ullam sunt beatae suscipit temporibus aliquam aspernatur minus amet. Eaque quidem alias fugit a aliquam autem ipsam similique repellat laudantium dolorum eius aspernatur nemo ad eos possimus, ratione consequuntur ullam. Architecto temporibus autem accusamus mollitia quidem esse, tenetur at reprehenderit sit laboriosam eveniet, distinctio odit eos asperiores. Sequi rem modi nihil fugiat optio dolorem neque ex commodi, maiores, ipsa maxime eveniet. Eius cum ipsum corrupti, nesciunt excepturi omnis ea quos earum vitae corporis quisquam incidunt necessitatibus, voluptatem quia assumenda provident totam ullam odio, quidem consequuntur! Ratione nostrum quidem molestiae iure blanditiis sit beatae earum recusandae esse, atque deserunt!
    Hic, accusamus voluptate porro nostrum placeat, totam quas beatae quo aliquam, fuga laborum tempore fugiat sit veritatis maxime. Vitae deleniti sapiente vel ex dolor dicta dolore iste totam nam saepe repellat expedita id ipsam suscipit, porro harum eius quis commodi recusandae quod doloremque consectetur quisquam. Nisi doloribus perspiciatis nostrum unde? Commodi ea facilis blanditiis consequuntur saepe suscipit veniam at accusamus eos odit provident ex, labore ducimus totam voluptas. Laborum perferendis neque dolore voluptatibus dicta quod deserunt beatae fuga sunt, tempore blanditiis, magnam quis soluta nihil ut iure cum unde placeat dolor repellendus officiis vitae. Adipisci iure minima vel laboriosam natus.
    Repudiandae ab numquam repellendus. Corrupti, in, cumque illum dolores eos possimus, quisquam officia nam consectetur et nemo mollitia reprehenderit esse! Possimus sunt deserunt fuga porro sequi, corporis, sint, labore distinctio voluptate maxime ducimus repudiandae nemo nihil? Distinctio necessitatibus quidem at repellendus quas aspernatur nostrum possimus, doloribus incidunt, provident magnam fuga cumque! Ipsa perferendis adipisci blanditiis! Modi nam ipsum minus vel omnis consequuntur aspernatur corrupti, non maxime illum nemo. Sequi nemo facere placeat vero ipsa delectus! Tenetur porro illum laboriosam animi expedita quae distinctio maxime, repellat saepe labore necessitatibus quibusdam facere ipsam et architecto nisi dolor accusantium inventore eos. Iusto, eligendi.
    Amet sit, impedit debitis nesciunt sapiente exercitationem cum vero. Placeat soluta veritatis cupiditate magnam, deserunt cumque voluptas distinctio. Placeat magni iste iusto sint eum fuga ipsum, perferendis aperiam impedit quam nulla quos nesciunt quisquam ratione, architecto repellendus reiciendis eveniet vel. Explicabo eos iure reprehenderit exercitationem harum, assumenda, consequuntur aliquid minima nemo tempora est officia aliquam nihil quia placeat suscipit rerum culpa illo perspiciatis. Sit laboriosam mollitia cupiditate, consequatur magnam ipsa quae totam illum, voluptates pariatur laborum velit fugiat culpa nostrum aperiam neque tempora? Earum aliquam ipsa provident at odit culpa, fugiat, itaque minima velit ipsam quibusdam, ut exercitationem cumque ipsum.
    Debitis saepe porro obcaecati ex, fugit quia deserunt eos quas asperiores ipsum architecto maxime nisi quos atque quisquam ipsa quam placeat quidem laboriosam cumque temporibus nobis amet dolores suscipit? Possimus velit reiciendis aliquam dolorem eaque nam quibusdam, fuga corporis omnis! Minus soluta, alias officiis animi veniam nihil laboriosam expedita minima maxime id impedit culpa beatae qui incidunt dicta ipsa porro, quas accusamus ipsum nobis aspernatur perferendis. Sequi maiores sunt natus cupiditate eveniet recusandae nulla perferendis inventore? Porro accusamus repellat quaerat quisquam consequatur ea soluta voluptates cumque sequi ut! Perferendis ad iste corporis temporibus blanditiis tempora mollitia. Itaque quibusdam necessitatibus vel.
    Culpa debitis dignissimos sit molestias possimus nesciunt a delectus necessitatibus, iure dicta. Ratione similique enim quidem, maxime ad accusamus debitis voluptas? Voluptatum suscipit molestias minus expedita excepturi illo cupiditate natus delectus, obcaecati officiis harum ut corporis neque possimus accusantium tenetur officia eveniet ad architecto magnam. Aliquid provident cum voluptate reiciendis sed voluptas voluptatem optio! Vero, possimus harum. Dignissimos reiciendis rerum autem, fugiat ipsum saepe sed pariatur eos magni facilis quidem ut dolores error ullam exercitationem? Tempore aperiam tenetur autem quidem perspiciatis deserunt, atque ex libero! Enim, fugit. Sed sint sapiente pariatur consequatur praesentium nulla voluptate impedit. Ullam, repellendus dignissimos? Consectetur.
    Debitis, neque. Id quos eius maiores vero, recusandae quia praesentium dolor ipsum doloremque alias ipsam pariatur deserunt repudiandae quisquam dignissimos. Expedita perspiciatis dolor non sunt consectetur, in blanditiis repellendus. Necessitatibus officiis consectetur nesciunt eaque quidem. Maxime reiciendis maiores reprehenderit nemo praesentium aliquid cupiditate nisi architecto doloremque in hic, eveniet itaque et voluptatum ipsa vitae voluptatem distinctio tenetur rerum quod. Eaque aut iure ducimus asperiores error excepturi perferendis, est debitis voluptatibus, dolorem animi consectetur provident? Dicta obcaecati ad minima eius. Tenetur ea quo aperiam eligendi dolores quasi magnam, impedit, ipsa quia hic et delectus reprehenderit beatae alias illum magni libero aspernatur!
    Cupiditate totam nulla molestiae rem voluptatibus. Enim reprehenderit eius in nobis? Adipisci numquam mollitia ratione fuga eligendi odio enim nostrum nemo, voluptatibus minus modi. Eaque quia deleniti pariatur eligendi impedit eos vitae necessitatibus saepe nesciunt ipsa expedita mollitia numquam et, quae nostrum ipsam, labore atque est nobis quaerat. Facere cupiditate vero voluptatum nemo commodi, impedit voluptatem consectetur beatae optio ullam ut minus quo quas eaque qui magni error sapiente porro unde veritatis facilis quidem. Recusandae consequuntur, quidem facilis porro eius, soluta exercitationem libero dignissimos quibusdam odio, consequatur cupiditate? Dignissimos quod id, animi tenetur impedit illum iusto. Animi omnis laborum voluptate.
  </p>
</div>
}

export default About;